name: Monthly Ticker Extraction

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:
  
jobs:
  tickers_extraction:
    environment: prd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Debug repo structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing top-level files:"
          ls -l
          echo "Listing airflow folder:"
          ls -l airflow
          echo "Listing dags folder:"
          ls -l airflow/dags
      
      - name: Debug Python path
        run: |
          python -c "import sys; print(sys.path)"

      - name: Run extract_listed_tickers.py
        run: |
          export PYTHONPATH=$(pwd)
          python airflow/dags/nasdaq_listed_tickers/extract_listed_tickers.py