name: Record Main Update

on:
  push:
    branches: [ main ]

jobs:
  record-push:
    runs-on: ubuntu-latest
    steps:
      - name: Create marker file
        run: echo "updated=true" > push_flag.txt

      - name: Upload artifact marker
        uses: actions/upload-artifact@v4
        with:
          name: main-updated-flag
          path: push_flag.txt
